Instrumenting fixes
vert-x3/vertx-sync pull request #17
Opened 2017-02-01 23:46 UTC by doctorpangloss

- Create tests to demonstrate nested awaits.
 - Create a better primitive, `awaitFiber`, that calls `awaitResult`'s argument in a Fiber.
 - Add `@Suspendable` to the interface implementations. This fixes the production issue I experienced where callsites were marked as uninstrumented in nested `awaitResult` calls:

```
WARNING: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at io.vertx.ext.sync.Sync.awaitFiber(java.util.function.Consumer) (Sync.java:78 bci: 113) !! (instrumented suspendable calls at: [])
```

2017-02-02 14:09 UTC, jponge requested changes
This looks like a sound addition.

The documentation should reflect the proposed change (see `src/main/java/io/vertx/ext/sync/package-info.java` from where the AsciiDoc is being extracted).

2017-02-02 18:19 UTC, doctorpangloss commented
Thanks, I'll fix package-info.java.

I should note that I experienced one more bug, which I don't believe I can fix using `vertx-sync`: I got a `SuspendExecution` exception only when a fiber yield (e.g., awaitResult) appeared inside a try block. I didn't test with Quasar 0.7.7.

But try throwing its own exception that it catches? Horrible!

2017-02-02 20:04 UTC, doctorpangloss commented
@jponge I'm going to try to reproduce the exception inside try-catch blocks and write the test for it. I can get it to reproduce on production code, which has a `com.sun.Proxy`, an `EventBus` handler and a lot of lambdas in between.

2017-02-02 20:35 UTC, jponge commented
Good, that'd be useful.

On Thu, Feb 2, 2017 at 9:04 PM, Benjamin Berman <notifications@github.com>
wrote:

> @jponge <https://github.com/jponge> I'm going to try to reproduce the
> exception inside try-catch blocks and write the test for it. I can get it
> to reproduce on production code, which has a com.sun.Proxy, an EventBus
> handler and a lot of lambdas in between.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/vert-x3/vertx-sync/pull/17#issuecomment-277067489>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABlaelBV4BNJVPrI0FbKg3JW1iJwiErks5rYjbpgaJpZM4L0ikD>
> .
>

2017-04-11 14:02 UTC, jan-zajic commented
Any news about this? It's important fix, we use our modified version (very similar) of vertx-sync in mean time.

2017-04-30 00:00 UTC, doctorpangloss commented
@jponge @jan-zajic I understand now that **any** code that might throw needs to be `@Suspendable`, even if it doesn't do any async work. This is because Quasar tries to serialize the continuation in the stack frame where an exception is thrown, not in the stack frame where the exception is handled. This means that basically all of the Vertx codebase needs `@Suspendable` on its methods, because it throws exceptions in so many places.

Quasar isn't super suitable for exception handling. I think the changes as I've written them should be merged, but I won't be able to give guidance on how to solve the exception handling problem generally.

2017-05-06 11:36 UTC, jan-zajic commented on src/main/java/io/vertx/ext/sync/impl/AsyncAdaptor.java
> +  @Suspendable
@doctorpangloss please make the same change in awaitEvent method

2017-05-06 11:37 UTC, jan-zajic commented
@doctorpangloss i think your idea in last comment is wrong. Can you post me some Gist with code that prove that behavior?

2018-04-05 12:43 UTC, closed without merging